# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(10000, 10000))
        self.centralwidget.setStyleSheet("background-color : black")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(900, 800))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget QWidget\n"
"{\n"
"background-color: rgb(49, 49, 49);\n"
"}\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"border-top: 2px solid rgb(49, 49, 49);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"padding-left : 5px;\n"
"padding-top: 5px;\n"
"min-height : 40px;\n"
"min-width : 150px;\n"
"background:  rgb(19, 19, 19);\n"
"border-top-left-radius: 8px;\n"
"border-top-right-radius: 8px;\n"
"border: 2px solid  rgb(49, 49, 49);\n"
"border-bottom-color:  rgb(49, 49, 49);\n"
"color : white;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background :  rgb(49, 49, 49);\n"
"}\n"
"\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDisplay = QtWidgets.QWidget()
        self.tabDisplay.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabDisplay.setFont(font)
        self.tabDisplay.setObjectName("tabDisplay")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabDisplay)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoPanelLayout = QtWidgets.QVBoxLayout()
        self.infoPanelLayout.setContentsMargins(10, -1, 10, -1)
        self.infoPanelLayout.setSpacing(2)
        self.infoPanelLayout.setObjectName("infoPanelLayout")
        self.infoframe = QtWidgets.QFrame(self.tabDisplay)
        self.infoframe.setMaximumSize(QtCore.QSize(150, 250))
        self.infoframe.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69)")
        self.infoframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoframe.setObjectName("infoframe")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.infoframe)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.infoVerticalLayout = QtWidgets.QVBoxLayout()
        self.infoVerticalLayout.setObjectName("infoVerticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.infoframe)
        self.frame_3.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.framesTotal = QtWidgets.QLabel(self.frame_3)
        self.framesTotal.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.framesTotal.setFont(font)
        self.framesTotal.setStyleSheet("color : white")
        self.framesTotal.setObjectName("framesTotal")
        self.verticalLayout_8.addWidget(self.framesTotal)
        self.totalFramesLCD = QtWidgets.QLCDNumber(self.frame_3)
        self.totalFramesLCD.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.totalFramesLCD.setFont(font)
        self.totalFramesLCD.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69);\n"
"color : white")
        self.totalFramesLCD.setSmallDecimalPoint(False)
        self.totalFramesLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.totalFramesLCD.setObjectName("totalFramesLCD")
        self.verticalLayout_8.addWidget(self.totalFramesLCD)
        self.infoVerticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.infoframe)
        self.frame_4.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.CellsAlive = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CellsAlive.setFont(font)
        self.CellsAlive.setStyleSheet("color : white")
        self.CellsAlive.setObjectName("CellsAlive")
        self.verticalLayout_7.addWidget(self.CellsAlive)
        self.AliveCellsLCD = QtWidgets.QLCDNumber(self.frame_4)
        self.AliveCellsLCD.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AliveCellsLCD.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69);\n"
"color : white")
        self.AliveCellsLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.AliveCellsLCD.setObjectName("AliveCellsLCD")
        self.verticalLayout_7.addWidget(self.AliveCellsLCD)
        self.infoVerticalLayout.addWidget(self.frame_4)
        self.gridLayout_6.addLayout(self.infoVerticalLayout, 0, 0, 1, 1)
        self.infoPanelLayout.addWidget(self.infoframe)
        self.horizontalLayout.addLayout(self.infoPanelLayout)
        self.mainField = QtWidgets.QFrame(self.tabDisplay)
        self.mainField.setMinimumSize(QtCore.QSize(800, 800))
        self.mainField.setMaximumSize(QtCore.QSize(800, 800))
        self.mainField.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69)")
        self.mainField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainField.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainField.setLineWidth(10)
        self.mainField.setMidLineWidth(16)
        self.mainField.setObjectName("mainField")
        self.horizontalLayout.addWidget(self.mainField)
        self.gameControlPanelsLayout = QtWidgets.QVBoxLayout()
        self.gameControlPanelsLayout.setContentsMargins(10, -1, 10, -1)
        self.gameControlPanelsLayout.setObjectName("gameControlPanelsLayout")
        self.gameContolPanel = QtWidgets.QFrame(self.tabDisplay)
        self.gameContolPanel.setMaximumSize(QtCore.QSize(150, 100))
        self.gameContolPanel.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69)")
        self.gameContolPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gameContolPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gameContolPanel.setObjectName("gameContolPanel")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gameContolPanel)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gameStartStopButton = QtWidgets.QPushButton(self.gameContolPanel)
        self.gameStartStopButton.setMinimumSize(QtCore.QSize(60, 60))
        self.gameStartStopButton.setMaximumSize(QtCore.QSize(60, 60))
        self.gameStartStopButton.setStyleSheet("QPushButton {\n"
"    border-radius : 5px;\n"
"    background-color : rgb(89, 89, 89)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(49, 49, 49);\n"
"    border-style: inset;\n"
"}")
        self.gameStartStopButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gameStartStopButton.setIcon(icon)
        self.gameStartStopButton.setIconSize(QtCore.QSize(40, 40))
        self.gameStartStopButton.setObjectName("gameStartStopButton")
        self.gridLayout_5.addWidget(self.gameStartStopButton, 0, 0, 1, 1)
        self.gameControlPanelsLayout.addWidget(self.gameContolPanel)
        self.pickToolPanel = QtWidgets.QFrame(self.tabDisplay)
        self.pickToolPanel.setMaximumSize(QtCore.QSize(150, 500))
        self.pickToolPanel.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69)")
        self.pickToolPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pickToolPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pickToolPanel.setObjectName("pickToolPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pickToolPanel)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.pickToolPanel)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color : white")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.pickButton = QtWidgets.QPushButton(self.frame)
        self.pickButton.setMaximumSize(QtCore.QSize(60, 60))
        self.pickButton.setStyleSheet("QPushButton {\n"
"    border-radius : 5px;\n"
"    background-color : rgb(0, 0, 0);\n"
"    border: 2pt solid black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 49, 49);\n"
"    border-style: inset;\n"
"}")
        self.pickButton.setText("")
        self.pickButton.setObjectName("pickButton")
        self.verticalLayout_4.addWidget(self.pickButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color : white")
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.pickToolPanel)
        self.frame_2.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color : white")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setStyleSheet("\n"
"QSpinBox {\n"
"border-radius : 5px;\n"
"background-color : rgb(69, 69, 69); \n"
"color : white;\n"
"padding-left : 5px;\n"
"padding-left : 20px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: center right; \n"
"border-image: url(:/icons/arrow_right.png);\n"
"border-right-width:10;\n"
"width: 10px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"border-right-width:30;    \n"
"subcontrol-position: center right ;\n"
"border-image: url(:/icons/arrow_left.png) 1;\n"
"width: 10px;\n"
"\n"
"}")
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setMaximum(4)
        self.spinBox_5.setObjectName("spinBox_5")
        self.verticalLayout_9.addWidget(self.spinBox_5)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color : white")
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_9.addWidget(self.radioButton_3)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.pickToolPanel)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_5.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius : 5px;\n"
"    background-color : rgb(69, 69, 69);\n"
"    color : white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(49, 49, 49);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_10.addWidget(self.pushButton)
        self.gridLayout_11.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gameControlPanelsLayout.addWidget(self.pickToolPanel)
        self.horizontalLayout.addLayout(self.gameControlPanelsLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/game_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabDisplay, icon1, "")
        self.tabSetting = QtWidgets.QWidget()
        self.tabSetting.setObjectName("tabSetting")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabSetting)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tabSetting)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 400))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69); color : white;")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 20, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ruleArriving = QtWidgets.QFrame(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ruleArriving.setFont(font)
        self.ruleArriving.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.ruleArriving.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ruleArriving.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ruleArriving.setObjectName("ruleArriving")
        self.ruleArriveLabel = QtWidgets.QLabel(self.ruleArriving)
        self.ruleArriveLabel.setGeometry(QtCore.QRect(10, 0, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ruleArriveLabel.setFont(font)
        self.ruleArriveLabel.setStyleSheet("border :  0px; color : white;")
        self.ruleArriveLabel.setTextFormat(QtCore.Qt.PlainText)
        self.ruleArriveLabel.setObjectName("ruleArriveLabel")
        self.verticalLayout_2.addWidget(self.ruleArriving)
        self.ruleSurviving = QtWidgets.QFrame(self.groupBox)
        self.ruleSurviving.setAutoFillBackground(False)
        self.ruleSurviving.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.ruleSurviving.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ruleSurviving.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ruleSurviving.setObjectName("ruleSurviving")
        self.ruleSurviveLabel = QtWidgets.QLabel(self.ruleSurviving)
        self.ruleSurviveLabel.setGeometry(QtCore.QRect(10, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ruleSurviveLabel.setFont(font)
        self.ruleSurviveLabel.setStyleSheet("border :  0px; border :  0px; color : white;")
        self.ruleSurviveLabel.setObjectName("ruleSurviveLabel")
        self.verticalLayout_2.addWidget(self.ruleSurviving)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ruleSurviveLabel_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ruleSurviveLabel_2.setFont(font)
        self.ruleSurviveLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ruleSurviveLabel_2.setAutoFillBackground(False)
        self.ruleSurviveLabel_2.setStyleSheet("border :  0px; border :  0px; color : white;")
        self.ruleSurviveLabel_2.setObjectName("ruleSurviveLabel_2")
        self.horizontalLayout_2.addWidget(self.ruleSurviveLabel_2)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setEnabled(True)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox.setStyleSheet("\n"
"QSpinBox {\n"
"border-radius : 5px;\n"
"background-color : rgb(89, 89, 89); \n"
"color : white;\n"
"padding-left : 5px;\n"
"padding-left : 20px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: center right; \n"
"border-image: url(:/icons/arrow_right.png);\n"
"border-right-width:10;\n"
"width: 10px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"border-right-width:30;    \n"
"subcontrol-position: center right ;\n"
"border-image: url(:/icons/arrow_left.png) 1;\n"
"width: 10px;\n"
"\n"
"}")
        self.spinBox.setFrame(True)
        self.spinBox.setSuffix("")
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(10, 20, 10, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fieldSettings = QtWidgets.QFrame(self.groupBox)
        self.fieldSettings.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(89, 89, 89)")
        self.fieldSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fieldSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fieldSettings.setObjectName("fieldSettings")
        self.ruleArriveLabel_3 = QtWidgets.QLabel(self.fieldSettings)
        self.ruleArriveLabel_3.setGeometry(QtCore.QRect(10, 10, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ruleArriveLabel_3.setFont(font)
        self.ruleArriveLabel_3.setStyleSheet("border :  0px; color : white;")
        self.ruleArriveLabel_3.setTextFormat(QtCore.Qt.PlainText)
        self.ruleArriveLabel_3.setObjectName("ruleArriveLabel_3")
        self.spinBox_3 = QtWidgets.QSpinBox(self.fieldSettings)
        self.spinBox_3.setGeometry(QtCore.QRect(60, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("\n"
"QSpinBox {\n"
"border-radius : 5px;\n"
"background-color : rgb(69, 69, 69); \n"
"color : white;\n"
"padding-left : 5px;\n"
"padding-left : 20px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: center right; \n"
"border-image: url(:/icons/arrow_right.png);\n"
"border-right-width:10;\n"
"width: 10px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"border-right-width:30;    \n"
"subcontrol-position: center right ;\n"
"border-image: url(:/icons/arrow_left.png) 1;\n"
"width: 10px;\n"
"\n"
"}")
        self.spinBox_3.setMinimum(4)
        self.spinBox_3.setMaximum(20)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.fieldSettings)
        self.spinBox_4.setGeometry(QtCore.QRect(240, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setStyleSheet("\n"
"QSpinBox {\n"
"border-radius : 5px;\n"
"background-color : rgb(69, 69, 69); \n"
"color : white;\n"
"padding-left : 5px;\n"
"padding-left : 20px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: center right; \n"
"border-image: url(:/icons/arrow_right.png);\n"
"border-right-width:10;\n"
"width: 10px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"border-right-width:30;    \n"
"subcontrol-position: center right ;\n"
"border-image: url(:/icons/arrow_left.png) 1;\n"
"width: 10px;\n"
"\n"
"}")
        self.spinBox_4.setMinimum(4)
        self.spinBox_4.setMaximum(20)
        self.spinBox_4.setObjectName("spinBox_4")
        self.ruleArriveLabel_4 = QtWidgets.QLabel(self.fieldSettings)
        self.ruleArriveLabel_4.setGeometry(QtCore.QRect(20, 50, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ruleArriveLabel_4.setFont(font)
        self.ruleArriveLabel_4.setStyleSheet("border :  0px; color : white;")
        self.ruleArriveLabel_4.setTextFormat(QtCore.Qt.PlainText)
        self.ruleArriveLabel_4.setObjectName("ruleArriveLabel_4")
        self.ruleArriveLabel_5 = QtWidgets.QLabel(self.fieldSettings)
        self.ruleArriveLabel_5.setGeometry(QtCore.QRect(200, 50, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ruleArriveLabel_5.setFont(font)
        self.ruleArriveLabel_5.setStyleSheet("border :  0px; color : white;")
        self.ruleArriveLabel_5.setTextFormat(QtCore.Qt.PlainText)
        self.ruleArriveLabel_5.setObjectName("ruleArriveLabel_5")
        self.verticalLayout_6.addWidget(self.fieldSettings)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.simulationSettings = QtWidgets.QGroupBox(self.tabSetting)
        self.simulationSettings.setMinimumSize(QtCore.QSize(0, 200))
        self.simulationSettings.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.simulationSettings.setFont(font)
        self.simulationSettings.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69); color : white;")
        self.simulationSettings.setObjectName("simulationSettings")
        self.ruleSurviveLabel_6 = QtWidgets.QLabel(self.simulationSettings)
        self.ruleSurviveLabel_6.setGeometry(QtCore.QRect(20, 50, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ruleSurviveLabel_6.setFont(font)
        self.ruleSurviveLabel_6.setStyleSheet("border :  0px; border :  0px; color : white;")
        self.ruleSurviveLabel_6.setObjectName("ruleSurviveLabel_6")
        self.fpsSetter = QtWidgets.QComboBox(self.simulationSettings)
        self.fpsSetter.setEnabled(True)
        self.fpsSetter.setGeometry(QtCore.QRect(70, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.fpsSetter.setFont(font)
        self.fpsSetter.setStyleSheet("QComboBox {\n"
"border-radius : 5px;\n"
"background-color : rgb(89, 89, 89); color : white;\n"
"}\n"
"\n"
"QComboBox::down-button {\n"
"subcontrol-origin: border;\n"
"border-right-width:30;    \n"
"subcontrol-position: center right ;\n"
"border-image: url(:/icons/arrow_left.png) 1;\n"
"width: 10px;\n"
"\n"
"}")
        self.fpsSetter.setObjectName("fpsSetter")
        self.fpsSetter.addItem("")
        self.fpsSetter.addItem("")
        self.fpsSetter.addItem("")
        self.fpsSetter.addItem("")
        self.fpsSetter.addItem("")
        self.fpsSetter.addItem("")
        self.fpsSetter.addItem("")
        self.verticalLayout.addWidget(self.simulationSettings)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/settings_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSetting, icon2, "")
        self.tabGraph = QtWidgets.QWidget()
        self.tabGraph.setObjectName("tabGraph")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabGraph)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plotSettingFrame = QtWidgets.QFrame(self.tabGraph)
        self.plotSettingFrame.setMaximumSize(QtCore.QSize(300, 400))
        self.plotSettingFrame.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69)")
        self.plotSettingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotSettingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotSettingFrame.setObjectName("plotSettingFrame")
        self.plotSettingsLabel = QtWidgets.QLabel(self.plotSettingFrame)
        self.plotSettingsLabel.setGeometry(QtCore.QRect(20, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.plotSettingsLabel.setFont(font)
        self.plotSettingsLabel.setStyleSheet("color : white")
        self.plotSettingsLabel.setObjectName("plotSettingsLabel")
        self.radioButton = QtWidgets.QRadioButton(self.plotSettingFrame)
        self.radioButton.setGeometry(QtCore.QRect(20, 50, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color : white")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.plotSettingFrame)
        self.plotFrame = QtWidgets.QFrame(self.tabGraph)
        self.plotFrame.setMinimumSize(QtCore.QSize(600, 400))
        self.plotFrame.setMaximumSize(QtCore.QSize(800, 600))
        self.plotFrame.setStyleSheet("border-radius : 5px;\n"
"background-color : rgb(69, 69, 69)")
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.horizontalLayout_3.addWidget(self.plotFrame)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/graph_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabGraph, icon3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convey"))
        self.framesTotal.setText(_translate("MainWindow", "Frame"))
        self.CellsAlive.setText(_translate("MainWindow", "Alive cells"))
        self.label.setText(_translate("MainWindow", "Current"))
        self.radioButton_2.setText(_translate("MainWindow", "Random"))
        self.label_2.setText(_translate("MainWindow", "Brush size"))
        self.radioButton_3.setText(_translate("MainWindow", "Random"))
        self.pushButton.setText(_translate("MainWindow", "Place"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDisplay), _translate("MainWindow", "Game"))
        self.groupBox.setTitle(_translate("MainWindow", "Game Rule Settings"))
        self.ruleArriveLabel.setText(_translate("MainWindow", "Cell arrives when neighbor count is"))
        self.ruleSurviveLabel.setText(_translate("MainWindow", "Cell survives when neighbor count is"))
        self.ruleSurviveLabel_2.setText(_translate("MainWindow", "Generations"))
        self.ruleArriveLabel_3.setText(_translate("MainWindow", "Field size"))
        self.ruleArriveLabel_4.setText(_translate("MainWindow", "X :"))
        self.ruleArriveLabel_5.setText(_translate("MainWindow", "Y:"))
        self.simulationSettings.setTitle(_translate("MainWindow", "Simultation Settings"))
        self.ruleSurviveLabel_6.setText(_translate("MainWindow", "FPS"))
        self.fpsSetter.setItemText(0, _translate("MainWindow", "5"))
        self.fpsSetter.setItemText(1, _translate("MainWindow", "10"))
        self.fpsSetter.setItemText(2, _translate("MainWindow", "20"))
        self.fpsSetter.setItemText(3, _translate("MainWindow", "30"))
        self.fpsSetter.setItemText(4, _translate("MainWindow", "40"))
        self.fpsSetter.setItemText(5, _translate("MainWindow", "50"))
        self.fpsSetter.setItemText(6, _translate("MainWindow", "60"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetting), _translate("MainWindow", "Settings"))
        self.plotSettingsLabel.setText(_translate("MainWindow", "Plot Settings"))
        self.radioButton.setText(_translate("MainWindow", "Enable total count"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGraph), _translate("MainWindow", "Plotter"))
import ico_res_rc
