# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 800)
        MainWindow.setMinimumSize(QtCore.QSize(900, 800))
        MainWindow.setMaximumSize(QtCore.QSize(900, 800))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color : black")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 900, 800))
        self.tabWidget.setStyleSheet("QTabWidget QWidget\n"
"{\n"
"background-color: black;\n"
"}\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"it reads QTabBar not QTabWidget */\n"
"QTabBar::tab {\n"
"min-height : 20px;\n"
"\n"
"background: gray;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background : white;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tabDisplay = QtWidgets.QWidget()
        self.tabDisplay.setObjectName("tabDisplay")
        self.mainField = QtWidgets.QFrame(self.tabDisplay)
        self.mainField.setGeometry(QtCore.QRect(10, 10, 880, 760))
        self.mainField.setStyleSheet("border-style: solid;\n"
"border: 4px;\n"
"border-color  : rgb(89, 89, 89);\n"
"border-bottom-color: black;\n"
"border-radius : 10px;\n"
"background-color : rgb(40, 40, 40)")
        self.mainField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainField.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainField.setLineWidth(10)
        self.mainField.setMidLineWidth(16)
        self.mainField.setObjectName("mainField")
        self.tabWidget.addTab(self.tabDisplay, "")
        self.tabSetting = QtWidgets.QWidget()
        self.tabSetting.setObjectName("tabSetting")
        self.ruleArriving = QtWidgets.QFrame(self.tabSetting)
        self.ruleArriving.setGeometry(QtCore.QRect(30, 30, 541, 80))
        self.ruleArriving.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ruleArriving.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ruleArriving.setObjectName("ruleArriving")
        self.ruleArriveLabel = QtWidgets.QLabel(self.ruleArriving)
        self.ruleArriveLabel.setGeometry(QtCore.QRect(10, 10, 231, 16))
        self.ruleArriveLabel.setObjectName("ruleArriveLabel")
        self.ruleSurviving = QtWidgets.QFrame(self.tabSetting)
        self.ruleSurviving.setGeometry(QtCore.QRect(30, 130, 541, 80))
        self.ruleSurviving.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ruleSurviving.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ruleSurviving.setObjectName("ruleSurviving")
        self.ruleSurviveLabel = QtWidgets.QLabel(self.ruleSurviving)
        self.ruleSurviveLabel.setGeometry(QtCore.QRect(10, 10, 231, 16))
        self.ruleSurviveLabel.setObjectName("ruleSurviveLabel")
        self.updateButton = QtWidgets.QPushButton(self.tabSetting)
        self.updateButton.setGeometry(QtCore.QRect(30, 250, 93, 28))
        self.updateButton.setStyleSheet("background-color : white")
        self.updateButton.setObjectName("updateButton")
        self.tabWidget.addTab(self.tabSetting, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convey"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDisplay), _translate("MainWindow", "Game"))
        self.ruleArriveLabel.setText(_translate("MainWindow", "Cell arrives when neighbor count is"))
        self.ruleSurviveLabel.setText(_translate("MainWindow", "Cell survives when neighbor count is"))
        self.updateButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetting), _translate("MainWindow", "Settings"))
